// SPDX-Licence-Identifier: EUPL-1.2

// Wails surface for the incidents service. Methods are bound on the
// *Service receiver and exposed to the frontend via wails3 generate
// bindings — the TS shape lands at
// frontend/bindings/dappco.re/lthn/desktop/pkg/incidents/service.

package incidents

import (
	core "dappco.re/go"
	"dappco.re/lthn/desktop/pkg/paths"
)

// List returns the incidents in the 90-day window, optionally filtered
// by state and/or severity. Results are sorted newest-first.
//
// Dual-format aware (RFC.stage-e-encrypt-at-rest v2 §4.1): .lthn files
// project HEADER-ONLY entries (Title / Svc / Who empty — the frontend
// renders an "encrypted" placeholder); .md legacy files round-trip
// the full plaintext entry. Reads-while-locked stays open — header
// MAC verify needs only the public key (no unlock required).
//
// Usage example:
//
//	r := svc.List(incidents.ListInput{State: "investigating"})
//	if r.OK { out := r.Value.(incidents.ListOutput) }
func (s *Service) List(input ListInput) core.Result {
	records, err := s.list90()
	if err != nil {
		return core.Fail(core.E("incidents.List", "scan failed", err))
	}

	now := core.Now()
	all := make([]IncidentEntry, 0, len(records))
	for _, r := range records {
		all = append(all, toEntry(r, now))
	}
	total := len(all)

	// Apply filters.
	limit := input.Limit
	if limit <= 0 {
		limit = 50
	}
	filtered := all[:0]
	for _, e := range all {
		if input.State != "" && e.State != input.State {
			continue
		}
		if input.Severity != "" && e.Sev != input.Severity {
			continue
		}
		filtered = append(filtered, e)
	}

	// Sort newest-first by TS is not reliable (it's relative text);
	// we rely on list90() reading directories in reverse-creation order.
	// Cap result set.
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}

	return core.Ok(ListOutput{
		Incidents: filtered,
		Total:     total,
	})
}

// Get returns a single incident by ID with the full post-mortem body.
//
// Stage E.D.B.2 surface (RFC.stage-e-encrypt-at-rest v2 §3.1):
// .lthn records require an unlocked session to decrypt the body. When
// loadOne reports the typed "incidents.session.locked" code (either
// the gate is unwired or no account is unlocked), Get forwards the
// session-locked failure verbatim so the frontend can distinguish
// "encrypted record needs unlock" from a true not-found.
//
// Usage example:
//
//	r := svc.Get(incidents.GetInput{ID: "2026-05-INC-001"})
//	if r.OK { detail := r.Value.(incidents.IncidentDetail) }
func (s *Service) Get(input GetInput) core.Result {
	if err := paths.IsValidID(input.ID); err != nil {
		return core.Fail(err)
	}
	rec, _, err := s.loadOne(input.ID)
	if err != nil {
		// Forward session.locked verbatim so the frontend can render
		// the unlock-prompt distinct from not-found.
		if core.Contains(err.Error(), "incidents.session.locked") {
			return core.Fail(err)
		}
		return core.Fail(core.E("incidents.Get", "not found: "+input.ID, err))
	}
	now := core.Now()
	return core.Ok(IncidentDetail{
		IncidentEntry: toEntry(rec, now),
		PostMortem:    rec.PostMortem,
	})
}

// Create opens a new incident, writes the Trix file to
// ~/Lethean/incidents/{YYYY}/{MM}/{id}.md, and fires the
// incidents.opened event.
//
// Usage example:
//
//	r := svc.Create(incidents.CreateInput{
//	    Title: "hub · elevated p99", Sev: "P3", Svc: "hub", Who: "Mei",
//	})
func (s *Service) Create(input CreateInput) core.Result {
	if fail, ok := s.assertUnlocked("incidents.Create"); !ok {
		return fail
	}
	if input.Title == "" {
		return core.Fail(core.E("incidents.Create", "title is required", nil))
	}
	if input.Sev == "" {
		input.Sev = "P3"
	}

	now := core.Now().UTC()
	dirR := yearMonthDir(now)
	if !dirR.OK {
		return core.Fail(core.E("incidents.Create", dirR.Error(), nil))
	}
	dirPath := dirR.Value.(string)

	// Generate ID: {YYYY}-{MM}-INC-{NNN}
	yr := core.TimeFormat(now, "2006")
	mo := core.TimeFormat(now, "01")
	n := countMonthFiles(dirPath) + 1
	id := core.Sprintf("%s-%s-INC-%03d", yr, mo, n)

	rec := IncidentRecord{
		ID:        id,
		Title:     input.Title,
		Sev:       input.Sev,
		State:     "investigating",
		Svc:       input.Svc,
		Who:       input.Who,
		Comments:  0,
		CreatedAt: now,
	}

	// Cascade W3 (RFC §B.3 row 8) — Create is an unconditional first-
	// write (ifVersion=0). writeRecord stamps Version=1 into the
	// marshalled frontmatter. Conflict-path (rare on Create — only
	// fires if another goroutine races on the same ID generated for
	// the same month) returns core.Fail(paths.ConflictEnvelope{...})
	// directly via writeRecord.
	//
	// 0o600 (Cerberus #1487 PR-1): post-mortem PII — owner-only at
	// rest, applied inside the primitive's atomic-rename path.
	// id is generated by Sprintf so traversal is structurally
	// impossible at this site, but the writeRecord helper validates
	// anyway.
	if wr := s.writeRecord(rec, dirPath, 0); !wr.OK {
		return wr
	}
	rec.Version = 1

	entry := toEntry(rec, now)
	s.fireEvent(EventOpened, entry)
	return core.Ok(entry)
}

// UpdateState transitions an incident's lifecycle state. When
// transitioning to "resolved", sets resolved_at and calculates
// dur_minutes. Fires the incidents.transitioned event.
//
// Usage example:
//
//	r := svc.UpdateState(incidents.UpdateStateInput{
//	    ID: "2026-05-INC-001", State: "resolved",
//	})
func (s *Service) UpdateState(input UpdateStateInput) core.Result {
	if fail, ok := s.assertUnlocked("incidents.UpdateState"); !ok {
		return fail
	}
	if err := paths.IsValidID(input.ID); err != nil {
		return core.Fail(err)
	}
	validStates := map[string]bool{
		"investigating": true,
		"post-mortem":   true,
		"resolved":      true,
	}
	if !validStates[input.State] {
		return core.Fail(core.E("incidents.UpdateState", "invalid state: "+input.State, nil))
	}

	rec, dirPath, err := s.loadOne(input.ID)
	if err != nil {
		if core.Contains(err.Error(), "incidents.session.locked") {
			return core.Fail(err)
		}
		return core.Fail(core.E("incidents.UpdateState", "not found: "+input.ID, err))
	}

	priorVersion := rec.Version
	rec.State = input.State
	if input.State == "resolved" && rec.ResolvedAt.IsZero() {
		rec.ResolvedAt = core.Now().UTC()
		if !rec.CreatedAt.IsZero() {
			dur := rec.ResolvedAt.Sub(rec.CreatedAt)
			rec.DurMinutes = int(dur.Minutes())
		}
	}

	// Cascade W3 (RFC §B.3 row 8) — IfVersion=priorVersion gates the
	// write under the primitive's optimistic-lock check.
	// priorVersion=0 (legacy file predating cutover) upgrades via an
	// unconditional first-write that stamps Version=1. Conflict-path
	// returns core.Fail(paths.ConflictEnvelope{...}) directly via
	// writeRecord (Mantis #1544 gating shape inherited from W1+W2).
	if wr := s.writeRecord(rec, dirPath, priorVersion); !wr.OK {
		return wr
	}
	rec.Version = priorVersion + 1
	if rec.Version < 1 {
		rec.Version = 1
	}

	entry := toEntry(rec, core.Now())
	s.fireEvent(EventTransitioned, entry)
	return core.Ok(entry)
}

// AddPostmortem attaches a markdown post-mortem to a resolved or
// post-mortem incident. Returns core.Fail when the incident is still
// in "investigating" state.
//
// Usage example:
//
//	r := svc.AddPostmortem(incidents.PostmortemInput{
//	    ID: "2026-05-INC-001", Body: "## Root cause\n\nDNS TTL too low.",
//	})
func (s *Service) AddPostmortem(input PostmortemInput) core.Result {
	if fail, ok := s.assertUnlocked("incidents.AddPostmortem"); !ok {
		return fail
	}
	if err := paths.IsValidID(input.ID); err != nil {
		return core.Fail(err)
	}

	rec, dirPath, err := s.loadOne(input.ID)
	if err != nil {
		if core.Contains(err.Error(), "incidents.session.locked") {
			return core.Fail(err)
		}
		return core.Fail(core.E("incidents.AddPostmortem", "not found: "+input.ID, err))
	}
	if rec.State == "investigating" {
		return core.Fail(core.E("incidents.AddPostmortem",
			"post-mortem requires state post-mortem or resolved, got: "+rec.State, nil))
	}

	priorVersion := rec.Version
	rec.PostMortem = input.Body
	// Cascade W3 (RFC §B.3 row 8) — IfVersion=priorVersion gates the
	// write under the primitive's optimistic-lock check. Same shape
	// as UpdateState above.
	if wr := s.writeRecord(rec, dirPath, priorVersion); !wr.OK {
		return wr
	}
	rec.Version = priorVersion + 1
	if rec.Version < 1 {
		rec.Version = 1
	}

	return core.Ok(toEntry(rec, core.Now()))
}
