import { defineConfig } from "vite";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = (p) => resolve(__dirname, p);

// Wails3 dev injects VITE_PORT=9245 via env (see root Taskfile.yml
// vars.VITE_PORT) and the Go binary connects to that URL via its
// AssetServer.DevServerURL config. Match the env or Wails sits in
// "Retrying..." until it gives up.
const port = Number(process.env.VITE_PORT) || 9245;

export default defineConfig({
  root: ".",
  publicDir: "public",
  // Path aliases — mirror tsconfig.json `paths`. Both must stay in
  // lockstep: tsc resolves at typecheck, Vite resolves at build.
  resolve: {
    alias: [
      { find: /^@\/(.*)$/,          replacement: root("src/$1") },
      { find: /^@ui\/(.*)$/,        replacement: root("src/lit/$1") },
      { find: /^@types$/,           replacement: root("src/lit/types.ts") },
      { find: /^@inference\/(.*)$/, replacement: root("bindings/dappco.re/go/inference/$1") },
      { find: /^@lthn\/(.*)$/,      replacement: root("bindings/dappco.re/go/$1") },
      { find: /^@desktop\/(.*)$/,   replacement: root("bindings/dappco.re/lthn/desktop/pkg/$1") },
      { find: /^@bindings\/(.*)$/,  replacement: root("bindings/$1") },
    ],
  },
  server: {
    port,
    strictPort: true,
    host: "localhost",
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
    target: "es2022",
    rollupOptions: {
      input: {
        index: "index.html",
        canvas: "canvas.html",
      },
    },
  },

  // Vitest config — Vitest reads `test` from the same vite.config so
  // the path aliases above work in tests too. happy-dom gives us
  // window + document + customElements without a real browser; v8
  // coverage is the lighter native backend (vs istanbul). Coverage
  // excludes the bindings tree (auto-generated by wails3 generate)
  // and the canvas dev page (design-preview harness).
  test: {
    environment: "happy-dom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.test.ts", "src/**/*.spec.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: ["src/**/*.ts"],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.spec.ts",
        "src/test/**",
        "bindings/**",
      ],
    },
  },
});
